=== Roguespider13/catan/php/gameXML.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 sp1 (http://www.altova.com) by Spider (Home) -->
<!--W3C Schema generated by XMLSpy v2013 sp1 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Wool">
		<xs:simpleType>
			<xs:restriction base="xs:int"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Wheat">
		<xs:simpleType>
			<xs:restriction base="xs:int"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Tiles">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Tile" minOccurs="16" maxOccurs="16"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Tile">
		<xs:complexType>
			<xs:attribute name="TRC" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="([SC]\.[a-zA-z0-9]{5,20})?"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="TR" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="([a-zA-z0-9]{5,20})?"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="TLC" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="([SC]\.[a-zA-z0-9]{5,20})?"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="Row" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:int">
						<xs:pattern value="[0-3]"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="ResType" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="wheat"/>
						<xs:enumeration value="wool"/>
						<xs:enumeration value="lumber"/>
						<xs:enumeration value="ore"/>
						<xs:enumeration value="desert"/>
						<xs:enumeration value="brick"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="RR" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="([a-zA-z0-9]{5,20})?"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="LR" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="([a-zA-z0-9]{5,20})?"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="DieNumber" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:int">
						<xs:pattern value="(1[0-2]|[2-9])"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="Col" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:int">
						<xs:pattern value="[0-3]"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="BRC" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="([SC]\.[a-zA-z0-9]{5,20})?"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="BR" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="([a-zA-z0-9]{5,20})?"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="BLC" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="([SC]\.[a-zA-z0-9]{5,20})?"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Robber">
		<xs:complexType>
			<xs:attribute name="Row" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:int">
						<xs:pattern value="[0-3]"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="Col" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:int">
						<xs:pattern value="[0-3]"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Resources">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Brick"/>
				<xs:element ref="Lumber"/>
				<xs:element ref="Ore"/>
				<xs:element ref="Wheat"/>
				<xs:element ref="Wool"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Points">
		<xs:simpleType>
			<xs:restriction base="xs:int"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Players">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Player" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="turn" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="([a-zA-z0-9]{5,20})?"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Player">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Points"/>
				<xs:element ref="Resources"/>
			</xs:sequence>
			<xs:attribute name="id" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[a-zA-z0-9]{5,20}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Ore">
		<xs:simpleType>
			<xs:restriction base="xs:int"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Lumber">
		<xs:simpleType>
			<xs:restriction base="xs:int"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="GameState">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="GameNumber">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="[0-9]{10}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="GameBoard">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Robber"/>
				<xs:element ref="Tiles"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="CatanGame">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="GameState"/>
				<xs:element ref="GameNumber"/>
				<xs:element ref="Players"/>
				<xs:element ref="GameBoard"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Brick">
		<xs:simpleType>
			<xs:restriction base="xs:int"/>
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== Roguespider13/catan/php/gameTemplate.xml
<?xml version="1.0" encoding="UTF-8"?>
<CatanGame xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Users/Spider/Documents/GitHub/catan/php/gameXML.xsd">
	<!-- 
	Valid Game States:
		Initial - initial settlement placements don't have requirement of roads to lead in.
		Ongoing - Normal game rules apply
		Complete - Game Over
	-->
	<GameState>Initial-0-Settlement</GameState>
	<GameNumber>1234567890</GameNumber>
	<Players turn="player1">
		<Player id="player1">
			<Points>0</Points>
			<Resources>
				<Brick>0</Brick>
				<Lumber>0</Lumber>
				<Ore>0</Ore>
				<Wheat>0</Wheat>
				<Wool>0</Wool>
			</Resources>
		</Player>
		<Player id="player2">
			<Points>0</Points>
			<Resources>
				<Brick>0</Brick>
				<Lumber>0</Lumber>
				<Ore>0</Ore>
				<Wheat>0</Wheat>
				<Wool>0</Wool>
			</Resources>
		</Player>
	</Players>
	<GameBoard>
		<Robber Row="0" Col="0"/>
		<Tiles>
			<Tile Row="0" Col="0" ResType="desert" DieNumber="10" TR="" LR="" RR="" BR="" TLC="" TRC="" BLC="" BRC=""/>
			<Tile Row="0" Col="1" ResType="desert" DieNumber="10" TR="" LR="" RR="" BR="" TLC="" TRC="" BLC="" BRC=""/>
			<Tile Row="0" Col="1" ResType="desert" DieNumber="10" TR="" LR="" RR="" BR="" TLC="" TRC="" BLC="" BRC=""/>
			<Tile Row="0" Col="3" ResType="desert" DieNumber="11" TR="" LR="" RR="" BR="" TLC="" TRC="" BLC="" BRC=""/>
			<Tile Row="1" Col="0" ResType="desert" DieNumber="11" TR="" LR="" RR="" BR="" TLC="" TRC="" BLC="" BRC=""/>
			<Tile Row="1" Col="1" ResType="desert" DieNumber="11" TR="" LR="" RR="" BR="" TLC="" TRC="" BLC="" BRC=""/>
			<Tile Row="1" Col="2" ResType="desert" DieNumber="11" TR="" LR="" RR="" BR="" TLC="" TRC="" BLC="" BRC=""/>
			<Tile Row="1" Col="3" ResType="desert" DieNumber="11" TR="" LR="" RR="" BR="" TLC="" TRC="" BLC="" BRC=""/>
			<Tile Row="2" Col="0" ResType="desert" DieNumber="11" TR="" LR="" RR="" BR="" TLC="" TRC="" BLC="" BRC=""/>
			<Tile Row="2" Col="1" ResType="desert" DieNumber="11" TR="" LR="" RR="" BR="" TLC="" TRC="" BLC="" BRC=""/>
			<Tile Row="2" Col="2" ResType="desert" DieNumber="11" TR="" LR="" RR="" BR="" TLC="" TRC="" BLC="" BRC=""/>
			<Tile Row="2" Col="3" ResType="desert" DieNumber="11" TR="" LR="" RR="" BR="" TLC="" TRC="" BLC="" BRC=""/>
			<Tile Row="3" Col="0" ResType="desert" DieNumber="11" TR="" LR="" RR="" BR="" TLC="" TRC="" BLC="" BRC=""/>
			<Tile Row="3" Col="1" ResType="desert" DieNumber="11" TR="" LR="" RR="" BR="" TLC="" TRC="" BLC="" BRC=""/>
			<Tile Row="3" Col="2" ResType="desert" DieNumber="11" TR="" LR="" RR="" BR="" TLC="" TRC="" BLC="" BRC=""/>
			<Tile Row="3" Col="3" ResType="desert" DieNumber="11" TR="" LR="" RR="" BR="" TLC="" TRC="" BLC="" BRC=""/>
		</Tiles>
	</GameBoard>
</CatanGame>
